services:
  - type: web
    name: selenium-app
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip chromium
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:10000
    envVars:
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
